#!/bin/bash

COMMIT_SHA=$(git rev-parse --short HEAD)
docker run -i --network youtoo_app-network -p 8181:8181 -e INGESTION_SNAPSHOTS_THRESHOLD=10 -e DATABASE_URL=$PROFILING_DATABASE_URL -e DATABASE_USERNAME=$PROFILING_DATABASE_USERNAME -e DATABASE_PASSWORD=$PROFILING_DATABASE_PASSWORD -p 10001:10001 --rm cqrs-profiling:$COMMIT_SHA

