image: docker:27.3.1-cli

services:
  - docker:27.3.1-dind

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: "tcp://docker:2375"

stages:
  - test
  - deploy

test:
  image: openjdk:17.0-jdk-oracle
  before_script:
    - ./sbt sbtVersion
  script:
    # Execute your project's tests
    - ./sbt clean test

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production
