services:

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: youtoo
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: youtoo
    networks:
      - app-network
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    networks:
      app-network:
        # This is the host name used in Kubernetes to access to DB
        aliases: [postgres]
    environment:
      ADMINER_DESIGN: 'pepa-linha'
      ADMINER_DEFAULT_SERVER: 'postgres'
    ports:
      - 8080:8080

volumes:
  postgres_data:
  grafana-storage:
networks:
  app-network:
    driver: bridge
