services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: cqrs
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cqrs
    networks:
      - cqrs-net
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    network_mode: "host"
    environment:
      ADMINER_DESIGN: 'pepa-linha'
      ADMINER_DEFAULT_SERVER: 'postgres'
    ports:
      - 8080:8080

volumes:
  postgres_data:
networks:
  cqrs-net:
    driver: bridge
