services:
  opensearch:
    image: opensearchproject/opensearch:2.18.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200" # OpenSearch REST API
      - "9600:9600" # OpenSearch performance monitoring
    networks:
      - app-network

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.18.0
    container_name: opensearch-dashboards
    environment:
      - 'OPENSEARCH_HOSTS=["https://opensearch:9200"]'
      - opensearch.username=admin
      - opensearch.password=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ports:
      - "5601:5601" # OpenSearch Dashboards UI
    networks:
      - app-network
    depends_on:
      - opensearch

  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: youtoo
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: youtoo
    networks:
      - app-network
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    networks:
      app-network:
        # This is the host name used in Kubernetes to access to DB
        aliases: [postgres]
    environment:
      ADMINER_DESIGN: 'pepa-linha'
      ADMINER_DEFAULT_SERVER: 'postgres'
    ports:
      - 8080:8080

volumes:
  postgres_data:
  opensearch-data:
networks:
  app-network:
    driver: bridge
