apiVersion: v1
kind: Service
metadata:
  name: youtoo-ingestion-service
  labels:
    app: youtoo-ingestion
spec:
  type: ClusterIP
  selector:
    app: youtoo-ingestion
  ports:
    - protocol: TCP
      port: 8181
      targetPort: 8181
