{
 "title": "Ingestion REST Endpoint Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Application Uptime (seconds)",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "application_uptime_seconds" }
   ]
  },
  {
   "title": "Active Requests",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_active_requests{}" }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(http_requests_total[1m])",
     "legendFormat": "{{http_method}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Request Rate for add_ingestion",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(http_requests_total{http_path=\"add_ingestion\"}[1m])",
     "legendFormat": "{{http_method}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Request Rate for add_ingestion_cmd",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(http_requests_total{http_path=\"add_ingestion_cmd\"}[1m])",
     "legendFormat": "{{http_method}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Request Rate for dataload_ingestions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(http_requests_total{http_path=\"dataload_ingestions\"}[1m])",
     "legendFormat": "{{http_method}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Request Rate for get_ingestion",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "rate(http_requests_total{http_path=\"get_ingestion\"}[1m])",
     "legendFormat": "{{http_method}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Request Rate for get_ingestion_keys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "rate(http_requests_total{http_path=\"get_ingestion_keys\"}[1m])",
     "legendFormat": "{{http_method}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Request Rate for validate_ingestion",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "rate(http_requests_total{http_path=\"validate_ingestion\"}[1m])",
     "legendFormat": "{{http_method}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Latency (95th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_milliseconds_bucket[1m]))",
     "legendFormat": "{{http_method}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Latency (95th Percentile) for add_ingestion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_milliseconds_bucket{http_path=\"add_ingestion\"}[1m]))",
     "legendFormat": "{{http_method}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Latency (95th Percentile) for add_ingestion_cmd",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_milliseconds_bucket{http_path=\"add_ingestion_cmd\"}[1m]))",
     "legendFormat": "{{http_method}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Latency (95th Percentile) for dataload_ingestions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_milliseconds_bucket{http_path=\"dataload_ingestions\"}[1m]))",
     "legendFormat": "{{http_method}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Latency (95th Percentile) for get_ingestion",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_milliseconds_bucket{http_path=\"get_ingestion\"}[1m]))",
     "legendFormat": "{{http_method}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Latency (95th Percentile) for get_ingestion_keys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 98 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_milliseconds_bucket{http_path=\"get_ingestion_keys\"}[1m]))",
     "legendFormat": "{{http_method}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Latency (95th Percentile) for validate_ingestion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 106 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_milliseconds_bucket{http_path=\"validate_ingestion\"}[1m]))",
     "legendFormat": "{{http_method}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 114 },
   "targets": [
    {
     "expr": "rate(http_requests_total{status_code=~\"5..\"}[1m])",
     "legendFormat": "{{http_method}} 5xx"
    },
    {
     "expr": "rate(http_requests_total{status_code=~\"4..\"}[1m])",
     "legendFormat": "{{http_method}} 4xx"
    }
   ]
  },
  {
   "title": "Error Rate for add_ingestion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 122 },
   "targets": [
    {
     "expr": "rate(http_requests_total{http_path=\"add_ingestion\",status_code=~\"5..\"}[1m])",
     "legendFormat": "{{http_method}} 5xx"
    },
    {
     "expr": "rate(http_requests_total{http_path=\"add_ingestion\",status_code=~\"4..\"}[1m])",
     "legendFormat": "{{http_method}} 4xx"
    }
   ]
  },
  {
   "title": "Error Rate for add_ingestion_cmd",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 130 },
   "targets": [
    {
     "expr": "rate(http_requests_total{http_path=\"add_ingestion_cmd\",status_code=~\"5..\"}[1m])",
     "legendFormat": "{{http_method}} 5xx"
    },
    {
     "expr": "rate(http_requests_total{http_path=\"add_ingestion_cmd\",status_code=~\"4..\"}[1m])",
     "legendFormat": "{{http_method}} 4xx"
    }
   ]
  },
  {
   "title": "Error Rate for dataload_ingestions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 138 },
   "targets": [
    {
     "expr": "rate(http_requests_total{http_path=\"dataload_ingestions\",status_code=~\"5..\"}[1m])",
     "legendFormat": "{{http_method}} 5xx"
    },
    {
     "expr": "rate(http_requests_total{http_path=\"dataload_ingestions\",status_code=~\"4..\"}[1m])",
     "legendFormat": "{{http_method}} 4xx"
    }
   ]
  },
  {
   "title": "Error Rate for get_ingestion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 146 },
   "targets": [
    {
     "expr": "rate(http_requests_total{http_path=\"get_ingestion\",status_code=~\"5..\"}[1m])",
     "legendFormat": "{{http_method}} 5xx"
    },
    {
     "expr": "rate(http_requests_total{http_path=\"get_ingestion\",status_code=~\"4..\"}[1m])",
     "legendFormat": "{{http_method}} 4xx"
    }
   ]
  },
  {
   "title": "Error Rate for get_ingestion_keys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 154 },
   "targets": [
    {
     "expr": "rate(http_requests_total{http_path=\"get_ingestion_keys\",status_code=~\"5..\"}[1m])",
     "legendFormat": "{{http_method}} 5xx"
    },
    {
     "expr": "rate(http_requests_total{http_path=\"get_ingestion_keys\",status_code=~\"4..\"}[1m])",
     "legendFormat": "{{http_method}} 4xx"
    }
   ]
  },
  {
   "title": "Error Rate for validate_ingestion",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 162 },
   "targets": [
    {
     "expr": "rate(http_requests_total{http_path=\"validate_ingestion\",status_code=~\"5..\"}[1m])",
     "legendFormat": "{{http_method}} 5xx"
    },
    {
     "expr": "rate(http_requests_total{http_path=\"validate_ingestion\",status_code=~\"4..\"}[1m])",
     "legendFormat": "{{http_method}} 4xx"
    }
   ]
  }
 ]
}