receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
      http:
        endpoint: localhost:4318
        cors:
          allowed_origins: [http://*, https://*]
  prometheus:
    config:
      scrape_configs:
        - job_name: otel-collector
          scrape_interval: 10s
          static_configs:
            - targets: [localhost:9464]
processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 75
    spike_limit_percentage: 15
  batch:
    send_batch_size: 10000
    timeout: 10s
extensions:
  health_check: {}
  # pprof: {}
  # zpages: {}
exporters:
  debug: {}
  prometheusremotewrite:
    endpoint: "http://prometheus-operated.monitoring.svc.cluster.local:9090/api/v1/write"
    target_info:
      enabled: true
    tls:
      insecure: true
  otlp/jaeger:
    endpoint: simple-jaeger-collector.observability.svc.cluster.local:4317
    tls:
      insecure: true
connectors:
  spanmetrics:
    namespace: span.metrics
service:
  # extensions: [health_check]
  # extensions: ["health_check", "pprof", "zpages"]
  pipelines:
    traces:
      receivers: [otlp]
      # processors: ["batch", "spanmetrics"]
      processors: [batch]
      exporters: [otlp/jaeger, spanmetrics, debug]
    metrics:
      receivers: [prometheus, otlp, spanmetrics]
      processors: [batch, memory_limiter]
      exporters: [prometheusremotewrite, debug]
  telemetry:
    metrics:
      address: 0.0.0.0:8888
